import AppKit
import TaplyneServer

/// Universal Clipboard is shared by all phones. Preserve rich representations and serialize use.
@MainActor final class ClipboardBridge {
    static let shared = ClipboardBridge()
    private var tail: Task<Void, Never>?

    func transaction<T: Sendable>(_ work: @escaping @MainActor (ClipboardLease) async throws -> T) async throws -> T {
        let previous = tail
        let task = Task { @MainActor in
            await previous?.value
            try Task.checkCancellation()
            let lease = ClipboardLease()
            defer { lease.restoreIfOwned() }
            return try await work(lease)
        }
        tail = Task { _ = try? await task.value }
        return try await withTaskCancellationHandler { try await task.value } onCancel: { task.cancel() }
    }
}

@MainActor final class ClipboardLease {
    private let board: NSPasteboard
    private let saved: [[NSPasteboard.PasteboardType: Data]]
    private var ownedCount: Int

    init(board: NSPasteboard = .general) {
        self.board = board
        let protectedTypes: Set<NSPasteboard.PasteboardType> = [
            .init("org.nspasteboard.ConcealedType"), .init("org.nspasteboard.TransientType"),
            .init("org.nspasteboard.AutoGeneratedType")
        ]
        saved = (board.pasteboardItems ?? []).compactMap { item in
            guard protectedTypes.isDisjoint(with: item.types) else { return nil }
            var types: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types { types[type] = item.data(forType: type) }
            return types
        }
        ownedCount = board.changeCount
    }

    func write(_ text: String) throws {
        guard board.changeCount == ownedCount else { throw PhoneServiceError.failed("CLIPBOARD_CHANGED: Clipboard changed during input. Input was stopped to preserve it.") }
        board.clearContents()
        guard board.setString(text, forType: .string) else { throw PhoneServiceError.failed("Could not write text to the clipboard.") }
        ownedCount = board.changeCount
    }

    func checkOwned() throws {
        guard board.changeCount == ownedCount else { throw PhoneServiceError.failed("CLIPBOARD_CHANGED: Clipboard changed before paste. Nothing was pasted.") }
    }

    /// Copy acknowledgments are bounded and never resend the original text.
    func receive(excluding sentinel: String, timeoutMs: Int) async throws -> String? {
        let deadline = Date().addingTimeInterval(Double(timeoutMs) / 1000)
        repeat {
            try Task.checkCancellation()
            if board.changeCount != ownedCount {
                guard let text = board.string(forType: .string), text != sentinel else { return nil }
                // The OS exposes no reliable source identity. Do not claim or later overwrite
                // a clipboard change which could have been made by the user.
                return text
            }
            try await Task.sleep(for: .milliseconds(40))
        } while Date() < deadline
        return nil
    }

    func restoreIfOwned() {
        guard board.changeCount == ownedCount else { return }
        board.prepareForNewContents(with: .currentHostOnly)
        let items = saved.map { types in
            let item = NSPasteboardItem()
            for (type, data) in types { item.setData(data, forType: type) }
            return item
        }
        if !items.isEmpty { board.writeObjects(items) }
    }
}
